#!/usr/bin/env python3
"""Export the optimised linkage as scad/walker_params.scad (all lengths in mm)."""
import json, sys
import numpy as np
import linkage6 as S, linkage_opt as L

cand_file = sys.argv[1] if len(sys.argv) > 1 else "candidates6_refined.json"
idx = int(sys.argv[2]) if len(sys.argv) > 2 else 1
a = float(sys.argv[3]) if len(sys.argv) > 3 else 9.0
c = json.load(open(cand_file))[idx]
b, d, dx, dz, pc, qc, e1, e2, x6, z6, pf, qf, br1, br2 = c["params"]
g = S.sixbar(c["params"]); m = L.stance_metrics(g["P"])
out = f"""// AUTO-GENERATED by design/gen_params.py - do not edit by hand.
// Six-bar leg synthesised by differential evolution (design/linkage6.py, refine6.py).
// Crank length a = {a} mm; every other length scaled from the optimiser (a = 1).
// Metrics @ a={a}: duty {m['duty']:.3f}, stride {m['stride']*a:.1f} mm, foot lift {m['lift']*a:.1f} mm,
//   min transmission angle {S.mu_min(g):.1f} deg, ground plane {m['zmin']*a:.2f} mm below crank axis.
a      = {a};
b      = {b*a:.4f};      // coupler A-B
d      = {d*a:.4f};      // rocker  O4-B
O4     = [{dx*a:.4f}, {dz*a:.4f}];   // rocker pivot (frame), crank axis = [0,0]
pc     = {pc*a:.4f};  qc = {qc*a:.4f};   // hinge point C on the coupler (along / across A->B)
e1     = {e1*a:.4f};      // foot link C-E
e2     = {e2*a:.4f};      // e-link  E-O6
O6     = [{x6*a:.4f}, {z6*a:.4f}];   // e-link pivot (frame)
pf     = {pf*a:.4f};  qf = {qf*a:.4f};   // foot P on the foot link (along / across C->E)
br1    = {int(br1)};  br2 = {int(br2)};      // circle-intersection branches
ground_z = {m['zmin']*a:.4f};         // flat stance height relative to crank axis
stride_mm = {m['stride']*a:.3f};
duty      = {m['duty']:.4f};
phase_stance_start_deg = {360.0*m['stance_idx'][0]/len(g['A']):.1f};
"""
open("../scad/walker_params.scad", "w").write(out)
print(out)
