#!/usr/bin/env python3
"""
Turn a photo/scan of your own pen drawing into a clean, closed silhouette SVG for OpenSCAD.

    python3 sketch_to_svg.py my_drawing.jpg body.svg [--width 120] [--thresh auto] [--smooth 2.0]

Pipeline: grayscale -> adaptive/Otsu threshold -> keep the largest outer contour (holes kept
as inner contours) -> Douglas-Peucker simplification -> mm-scaled SVG path (y flipped so that
OpenSCAD's import() keeps the drawing upright).
"""
import argparse
import sys
import cv2
import numpy as np


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image"); ap.add_argument("out_svg")
    ap.add_argument("--scad", default=None, help="also write an OpenSCAD polygon module (default: next to the svg)")
    ap.add_argument("--width", type=float, default=120.0, help="silhouette width in mm")
    ap.add_argument("--thresh", default="auto", help="'auto' (Otsu) or 0-255")
    ap.add_argument("--smooth", type=float, default=2.0, help="blur sigma in px before threshold")
    ap.add_argument("--simplify", type=float, default=0.0015, help="DP epsilon as fraction of contour length")
    ap.add_argument("--close", type=int, default=9, help="morphological close kernel (px) to seal pen gaps")
    ap.add_argument("--fill", action="store_true", help="fill the enclosed outline (use for line drawings)")
    ap.add_argument("--engrave", action="store_true", help="keep the pen strokes INSIDE the outline as engraved lines (eyes, mouth, patterns)")
    ap.add_argument("--stroke-min", type=float, default=0.6, help="drop engraved details smaller than this many mm")
    a = ap.parse_args()

    img = cv2.imread(a.image)
    if img is None:
        sys.exit(f"cannot read {a.image}")
    g = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    if a.smooth > 0:
        g = cv2.GaussianBlur(g, (0, 0), a.smooth)
    if a.thresh == "auto":
        _, bw = cv2.threshold(g, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    else:
        _, bw = cv2.threshold(g, int(a.thresh), 255, cv2.THRESH_BINARY_INV)
    if a.close > 0:
        k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (a.close, a.close))
        bw = cv2.morphologyEx(bw, cv2.MORPH_CLOSE, k)
    mode = cv2.RETR_EXTERNAL if a.fill else cv2.RETR_CCOMP
    cnts, hier = cv2.findContours(bw, mode, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        sys.exit("no contour found - try --thresh or a darker pen")
    big = max(cnts, key=cv2.contourArea)
    x, y, w, h = cv2.boundingRect(big)
    scale = a.width / w
    paths = []
    scad_pts, scad_paths = [], []
    for i, c in enumerate(cnts):
        if cv2.contourArea(c) < 0.0005 * cv2.contourArea(big):
            continue
        # keep the main silhouette and its direct holes only
        if not a.fill and hier is not None and hier[0][i][3] not in (-1,) and cnts[hier[0][i][3]] is not big:
            if not np.array_equal(cnts[hier[0][i][3]], big):
                continue
        eps = a.simplify * cv2.arcLength(c, True)
        ap_ = cv2.approxPolyDP(c, eps, True)[:, 0, :].astype(float)
        pts = [((px - x) * scale, (h - (py - y)) * scale) for px, py in ap_]
        scad_paths.append(list(range(len(scad_pts), len(scad_pts) + len(pts))))
        scad_pts.extend(pts)
        paths.append("M " + " L ".join(f"{px:.3f},{-py:.3f}" for px, py in pts) + " Z")
    H = h * scale
    line_pts, line_paths = [], []
    if a.engrave:
        fill = np.zeros_like(bw)
        cv2.drawContours(fill, [big], -1, 255, thickness=cv2.FILLED)
        inner = cv2.erode(fill, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (max(3, int(0.012 * w)) | 1,) * 2))
        strokes = cv2.bitwise_and(bw, inner)
        lc, _ = cv2.findContours(strokes, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
        for c in lc:
            if cv2.contourArea(c) * scale * scale < a.stroke_min ** 2:
                continue
            ap2 = cv2.approxPolyDP(c, 0.003 * cv2.arcLength(c, True), True)[:, 0, :].astype(float)
            if len(ap2) < 3:
                continue
            pts = [((px - x) * scale, (h - (py - y)) * scale) for px, py in ap2]
            line_paths.append(list(range(len(line_pts), len(line_pts) + len(pts)))); line_pts.extend(pts)
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" width="{a.width:.2f}mm" height="{H:.2f}mm" '
           f'viewBox="0 {-H:.3f} {a.width:.3f} {H:.3f}">\n'
           f'<path fill="black" fill-rule="evenodd" d="{" ".join(paths)}"/>\n</svg>\n')
    open(a.out_svg, "w").write(svg)
    scad_file = a.scad or a.out_svg.rsplit(".", 1)[0] + "_outline.scad"
    pts_txt = ",".join(f"[{px:.3f},{py:.3f}]" for px, py in scad_pts)
    open(scad_file, "w").write(
        f"// generated by sketch_to_svg.py from {a.image.split('/')[-1]} -- origin = bbox min, +y up, mm\n"
        f"body_w = {a.width:.3f};\nbody_h = {H:.3f};\n"
        f"body_pts = [{pts_txt}];\nbody_paths = {scad_paths};\n"
        f"module body_2d() {{ polygon(points = body_pts, paths = body_paths); }}\n"
        f"has_lines = {'true' if line_pts else 'false'};\n"
        f"lines_pts = [{','.join(f'[{px:.3f},{py:.3f}]' for px, py in line_pts)}];\nlines_paths = {line_paths};\n"
        f"module lines_2d() {{ if (has_lines) polygon(points = lines_pts, paths = lines_paths); }}\n")
    if a.engrave:
        print(f"engraving: {len(line_paths)} stroke region(s)")
    print("wrote", scad_file)
    print(f"wrote {a.out_svg}: {len(paths)} contour(s), {a.width:.0f} x {H:.0f} mm, "
          f"{sum(len(p.split('L')) for p in paths)} points")


if __name__ == "__main__":
    main()
