// AUTO-GENERATED by design/gen_params.py - do not edit by hand.
// Six-bar leg synthesised by differential evolution (design/linkage6.py, refine6.py).
// Crank length a = 9.0 mm; every other length scaled from the optimiser (a = 1).
// Metrics @ a=9.0: duty 0.619, stride 35.5 mm, foot lift 14.3 mm,
//   min transmission angle 36.1 deg, ground plane -44.04 mm below crank axis.
a      = 9.0;
b      = 14.4228;      // coupler A-B
d      = 25.0519;      // rocker  O4-B
O4     = [-11.3389, -22.1390];   // rocker pivot (frame), crank axis = [0,0]
pc     = 21.0050;  qc = -4.6461;   // hinge point C on the coupler (along / across A->B)
e1     = 26.0334;      // foot link C-E
e2     = 25.6168;      // e-link  E-O6
O6     = [-3.9532, 26.3372];   // e-link pivot (frame)
pf     = -26.6494;  qf = -49.3749;   // foot P on the foot link (along / across C->E)
br1    = -1;  br2 = -1;      // circle-intersection branches
ground_z = -44.0386;         // flat stance height relative to crank axis
stride_mm = 35.534;
duty      = 0.6194;
phase_stance_start_deg = 301.5;
