// =====================================================================
//  Vein-Glow Lantern  -  base and calibration wedge
//  Autumn Nest contest, entry #10 (A Forest Corner: lamps)
//
//  The shade (stl/shade.stl) is a lithophane: the leaf veins are thin wall and glow, the
//  leaf blade is medium, the background is thick and dark. It is generated by
//  tools/vein_field.py + tools/blender_vein_shade.py. This file makes everything that has
//  to fit it: the base with a seat for the shade and a pocket for the LED, and a step wedge
//  that lets you calibrate wall thickness against your own filament and LED.
//
//  LIGHT SOURCE: a warm-white LED only (battery tealight or a USB LED puck, max 1 W).
//  Never an incandescent, halogen or any bulb above 1 W: PLA softens at about 55 C.
//
//  Tested with OpenSCAD 2021.01.
// =====================================================================

/* [Part to render] */
// base = lamp base, wedge = wall-thickness calibration wedge
part = "base"; // [base, wedge]

/* [Shade interface - must match vein_field.py / blender_vein_shade.py] */
// Outer radius of the shade at its bottom edge (mm), vein_field.py --r-bottom
shade_r0 = 36;
// Wall thickness of the plain bottom rim of the shade (mm)
rim_t = 2.4;
// Clearance between the base lip and the inside of the shade rim (mm)
clr = 0.35;

/* [Base] */
base_r = 46;
base_h = 12;
// Height and thickness of the lip that centres the shade (mm)
lip_h = 6;
lip_t = 2;

/* [LED] */
// Diameter of the LED tealight or puck (mm). Common tealights are 38-39 mm
led_d = 38.5;
// Depth of the pocket that holds it (mm)
led_pocket = 3;
// Height of the riser post under the LED (mm). Sets where the light sits inside the shade:
// emission height above the shade's bottom edge = riser_h - led_pocket + led_emit_h.
// tools/lamp_light.py finds ~31 mm gives the most even glow top to bottom; 17 mm does that for a tealight
riser_h = 17;
// Height of the light-emitting part above the bottom of the LED body (mm): a tealight's LED is near its top
led_emit_h = 17;
// Cut a groove for a USB cable (a 5 V USB LED puck)
usb_groove = true;
usb_w = 6;
usb_depth = 3.5;

/* [Calibration wedge] */
wedge_steps = [0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6];
step_w = 10;
step_h = 30;

/* [Quality] */
$fn = 120;

lip_ro = shade_r0 - rim_t - clr;      // outer radius of the lip
lip_ri = lip_ro - lip_t;

module base() {
    post_d = led_d + 5.5;
    difference() {
        union() {
            // body with a 2 mm chamfer at the bottom edge (no sharp bed-contact edge)
            cylinder(r1 = base_r - 2, r2 = base_r, h = 2);
            translate([0, 0, 2]) cylinder(r = base_r, h = base_h - 2);
            // lip that centres the shade
            translate([0, 0, base_h - 0.01]) difference() {
                cylinder(r = lip_ro, h = lip_h + 0.01);
                translate([0, 0, -1]) cylinder(r = lip_ri, h = lip_h + 2);
            }
            // riser post under the LED
            translate([0, 0, base_h - 0.01]) cylinder(d = post_d, h = riser_h + 0.01);
        }
        // LED pocket at the top of the post
        translate([0, 0, base_h + riser_h - led_pocket]) cylinder(d = led_d + 1.0, h = led_pocket + 1);
        // cable groove: down the post (toward -y), then across the base to the edge, through the lip too
        if (usb_groove) {
            translate([-usb_w / 2, -post_d / 2 - 1, base_h - usb_depth])
                cube([usb_w, usb_depth + 1, usb_depth + riser_h + 1]);
            translate([-usb_w / 2, -base_r - 1, base_h - usb_depth])
                cube([usb_w, base_r - post_d / 2 + 1, usb_depth + lip_h + 1]);
        }
    }
}

// a lithophane step wedge: stands on its edge like the lamp wall, thickness grows to the right
module wedge() {
    n = len(wedge_steps);
    cube([n * step_w, max(wedge_steps), 1.2]);                       // joining rail
    for (i = [0 : n - 1])
        translate([i * step_w, 0, 0]) cube([step_w, wedge_steps[i], step_h]);
}

if (part == "wedge") wedge();
else base();

echo(str("lip outer radius ", lip_ro, " mm, shade rim inner radius ", shade_r0 - rim_t, " mm"));
echo(str("LED emission height above the shade bottom edge: ", riser_h - led_pocket + led_emit_h, " mm"));
