// =====================================================================
//  Vein-Glow Lantern  -  base and calibration wedge
//  Autumn Nest contest, entry #10 (A Forest Corner: lamps)
//
//  The shade (stl/shade.stl) is a lithophane: the leaf veins are thin wall and glow, the
//  leaf blade is medium, the background is thick and dark. It is generated by
//  tools/vein_field.py + tools/blender_vein_shade.py. This file makes everything that has
//  to fit it: the base with a seat for the shade and a pocket for the LED, and a step wedge
//  that lets you calibrate wall thickness against your own filament and LED.
//
//  LIGHT SOURCE: the Bambu Lab LED Lamp Kit 001 (MH001), a round warm-white puck, 5 V USB, 3 W.
//  The base is sized for it (diameter 59 mm). Other flat round pucks work by changing led_d / led_h.
//  Never an incandescent or halogen bulb: PLA softens at about 55 C.
//
//  Tested with OpenSCAD 2021.01.
// =====================================================================

/* [Part to render] */
// base = lamp base, wedge = wall-thickness calibration wedge
part = "base"; // [base, wedge]

/* [Shade interface - must match vein_field.py / blender_vein_shade.py] */
// Outer radius of the shade at its bottom edge (mm), vein_field.py --r-bottom
shade_r0 = 36;
// Wall thickness of the plain bottom rim of the shade (mm)
rim_t = 2.4;
// Clearance between the base lip and the inside of the shade rim (mm)
clr = 0.35;

/* [Base] */
base_r = 46;
base_h = 12;
// Height and thickness of the lip that centres the shade (mm)
lip_h = 6;
lip_t = 2;

/* [LED: Bambu Lab LED Lamp Kit 001 (MH001) round puck] */
// Diameter of the puck (mm). Listed as D59 by every retailer found
led_d = 59;
// Height of the puck (mm). Most listings say 18, a few say 8: MEASURE YOURS and enter it here
led_h = 18;
// Height of the puck's lit face above the shade's seat (mm). tools/lamp_light.py finds 34 mm
// lights the veins at the top and bottom of the shade most evenly. The post under the puck is
// face_z - led_h tall, so a different led_h keeps the light at the same height
face_z = 34;
// Diameter of the double-sided tape that comes with the kit (mm): it holds the puck on the post
tape_d = 40;
// Cut a groove for the 1.5 m USB cable: down the post and across the base to the edge
usb_groove = true;
usb_w = 6;
usb_depth = 3.5;

/* [Calibration wedge] */
wedge_steps = [0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6];
step_w = 10;
step_h = 30;

/* [Quality] */
$fn = 120;

lip_ro = shade_r0 - rim_t - clr;      // outer radius of the lip
lip_ri = lip_ro - lip_t;

post_h = max(0, face_z - led_h);        // post under the puck
sink   = max(0, led_h - face_z);        // pocket depth if the puck has to sit lower than its own height
post_d = tape_d + 4;                    // the tape sticks the puck to the top of the post

module base() {
    groove_r = post_h > 0 ? post_d / 2 : (led_d + 1) / 2;
    difference() {
        union() {
            // body with a 2 mm chamfer at the bottom edge (no sharp bed-contact edge)
            cylinder(r1 = base_r - 2, r2 = base_r, h = 2);
            translate([0, 0, 2]) cylinder(r = base_r, h = base_h - 2);
            // lip that centres the shade
            translate([0, 0, base_h - 0.01]) difference() {
                cylinder(r = lip_ro, h = lip_h + 0.01);
                translate([0, 0, -1]) cylinder(r = lip_ri, h = lip_h + 2);
            }
            // post under the puck
            if (post_h > 0) translate([0, 0, base_h - 0.01]) cylinder(d = post_d, h = post_h + 0.01);
        }
        // pocket, only when the puck has to sit lower than its own height
        if (sink > 0) translate([0, 0, base_h - sink]) cylinder(d = led_d + 1.0, h = sink + 1);
        // cable groove: down the post (toward -y), then across the base to the edge, through the lip too
        if (usb_groove) {
            if (post_h > 0)
                translate([-usb_w / 2, -groove_r - 1, base_h - usb_depth])
                    cube([usb_w, usb_depth + 1, usb_depth + post_h + 1]);
            translate([-usb_w / 2, -base_r - 1, base_h - usb_depth])
                cube([usb_w, base_r - groove_r + 1, usb_depth + lip_h + 1]);
        }
    }
}

// a lithophane step wedge: stands on its edge like the lamp wall, thickness grows to the right
module wedge() {
    n = len(wedge_steps);
    cube([n * step_w, max(wedge_steps), 1.2]);                       // joining rail
    for (i = [0 : n - 1])
        translate([i * step_w, 0, 0]) cube([step_w, wedge_steps[i], step_h]);
}

if (part == "wedge") wedge();
else base();

echo(str("lip outer radius ", lip_ro, " mm, shade rim inner radius ", shade_r0 - rim_t, " mm"));
echo(str("puck underside ", base_h + post_h - sink, " mm, lit face ", face_z, " mm above the shade seat; post ", post_h, " mm"));
