// =====================================================================
//  Vein-Glow Lantern  -  base and calibration wedge
//  Autumn Nest contest, entry #10 (A Forest Corner: lamps)
//
//  The shade (stl/shade.stl) is a lithophane: the leaf veins are thin wall and glow, the
//  leaf blade is medium, the background is thick and dark. It is generated by
//  tools/vein_field.py + tools/blender_vein_shade.py. This file makes everything that has
//  to fit it: the base with a seat for the shade and a pocket for the LED, and a step wedge
//  that lets you calibrate wall thickness against your own filament and LED.
//
//  LIGHT SOURCE: the Bambu Lab LED Lamp Kit 001 (MH001), a round warm-white puck, 5 V USB, 3 W.
//  The base holds the 59 x 9 mm module in a tray (pocket). Other flat round modules work by changing led_d / led_h.
//  Print part = "led_fit" first (about 10 minutes) to check your module fits before printing the whole base.
//  Never an incandescent or halogen bulb: PLA softens at about 55 C.
//
//  Tested with OpenSCAD 2021.01.
// =====================================================================

/* [Part to render] */
// base = lamp base, wedge = wall-thickness calibration wedge, led_fit = small test piece: print it first to check the LED fits
part = "base"; // [base, wedge, led_fit]

/* [Shade interface - must match vein_field.py / blender_vein_shade.py] */
// Outer radius of the shade at its bottom edge (mm), vein_field.py --r-bottom
shade_r0 = 36;
// Wall thickness of the plain bottom rim of the shade (mm)
rim_t = 2.4;
// Clearance between the base lip and the inside of the shade rim (mm)
clr = 0.35;

/* [Base] */
base_r = 46;
base_h = 12;
// Height and thickness of the lip that centres the shade (mm)
lip_h = 6;
lip_t = 2;

/* [LED: Bambu Lab LED Lamp Kit 001 (MH001) round module] */
// Diameter of the module (mm): 59 (about; the real one may measure up to 60)
led_d = 59;
// Height of the module (mm): about 9 (retailers list 18 or 8, one measurement said 10)
led_h = 9;
// Total clearance between the module and the pocket wall (mm). 1.6 gives a 60.6 mm pocket, so a module
// of 59 to 60.4 mm fits; the module is held by the pocket wall and the kit's double-sided tape
led_clr = 1.6;
// Height of the module's lit face above the shade's seat (mm). tools/lamp_light.py finds 34 mm
// lights the veins at the top and bottom of the shade most evenly. The tray floor is raised to
// face_z - led_h, so a different led_h keeps the light at the same height
face_z = 34;
// How deep the module sits in the pocket (mm)
pocket_depth = 8;
// Cable groove (1.5 m USB cable): a notch in the tray wall, down the tray and across the base to the edge
usb_groove = true;
usb_w = 6;
usb_depth = 3.5;

/* [Calibration wedge] */
wedge_steps = [0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6];
step_w = 10;
step_h = 30;

/* [Quality] */
$fn = 120;

lip_ro = shade_r0 - rim_t - clr;      // outer radius of the lip
lip_ri = lip_ro - lip_t;

floor_z  = max(0, face_z - led_h);      // the pocket floor above the shade's seat
tray_h   = floor_z + pocket_depth;      // top of the tray above the seat
pocket_r = (led_d + led_clr) / 2;
tray_r   = lip_ro;                      // the tray is also the lip that centres the shade

assert(tray_r - pocket_r >= 2, "tray wall too thin: the module is too wide for this shade");

module cable_notch(z0, h) {
    translate([-usb_w / 2, -tray_r - 1, z0]) cube([usb_w, tray_r - pocket_r + 2, h]);
}

module base() {
    difference() {
        union() {
            // body with a 2 mm chamfer at the bottom edge (no sharp bed-contact edge)
            cylinder(r1 = base_r - 2, r2 = base_r, h = 2);
            translate([0, 0, 2]) cylinder(r = base_r, h = base_h - 2);
            // tray: its outer wall centres the shade (0.35 mm clearance), its pocket holds the LED module
            translate([0, 0, base_h - 0.01]) cylinder(r = tray_r, h = tray_h + 0.01);
        }
        translate([0, 0, base_h + floor_z]) cylinder(r = pocket_r, h = pocket_depth + 1);
        if (usb_groove) {
            cable_notch(base_h + floor_z, pocket_depth + 1);                       // window in the tray wall
            translate([-usb_w / 2, -tray_r - 1, base_h - usb_depth])               // down the outside of the tray
                cube([usb_w, 4, floor_z + pocket_depth + usb_depth + 1]);
            translate([-usb_w / 2, -base_r - 1, base_h - usb_depth])               // across the base, under the shade rim
                cube([usb_w, base_r - tray_r + 4, usb_depth + 1]);
        }
    }
}

// quick fit test: the top of the tray only (3 mm floor, the pocket and the cable notch)
module led_fit() {
    difference() {
        cylinder(r = tray_r, h = pocket_depth + 3);
        translate([0, 0, 3]) cylinder(r = pocket_r, h = pocket_depth + 1);
        if (usb_groove) cable_notch(3, pocket_depth + 1);
    }
}

// a lithophane step wedge: stands on its edge like the lamp wall, thickness grows to the right
module wedge() {
    n = len(wedge_steps);
    cube([n * step_w, max(wedge_steps), 1.2]);                       // joining rail
    for (i = [0 : n - 1])
        translate([i * step_w, 0, 0]) cube([step_w, wedge_steps[i], step_h]);
}

if (part == "wedge") wedge();
else if (part == "led_fit") led_fit();
else base();

echo(str("lip outer radius ", lip_ro, " mm, shade rim inner radius ", shade_r0 - rim_t, " mm"));
echo(str("module bottom ", floor_z, " mm and lit face ", face_z, " mm above the shade seat; tray ", tray_h, " mm tall, pocket diameter ", 2 * pocket_r, " mm"));
