"""All user-visible text: key -> (Korean, English). Keep both languages in sync (tests check this)."""

STRINGS: dict[str, tuple[str, str]] = {}


def _a(d: dict[str, tuple[str, str]]) -> None:
    STRINGS.update(d)


# ------------------------------------------------------------------ stages
_a({
    "stage.prompt": ("프롬프트 분석", "Prompt analysis"),
    "stage.connect": ("클라우드 GPU 연결", "Cloud GPU connection"),
    "stage.generate": ("피규어 생성", "Figure generation"),
    "stage.download": ("메시 다운로드", "Downloading mesh"),
    "stage.validate": ("메시 검사", "Mesh validation"),
    "stage.repair": ("메시 복구", "Mesh repair"),
    "stage.optimize": ("출력 최적화", "Print optimization"),
    "stage.color_analysis": ("색상 분석", "Color analysis"),
    "stage.color_reduce": ("색상 줄이기", "Color reduction"),
    "stage.export": ("3MF 생성", "3MF generation"),
    "stage.ready": ("준비 완료", "Ready"),
})

# ------------------------------------------------------------------ errors
_a({
    "err.unknown": ("알 수 없는 오류가 발생했습니다: {detail}", "An unexpected error occurred: {detail}"),
    "err.cancelled": ("작업이 취소되었습니다.", "The operation was cancelled."),
    "err.no_internet": ("인터넷에 연결할 수 없습니다. 네트워크를 확인하세요.", "No internet connection. Check your network."),
    "err.server_unavailable": ("GPU 서버에 연결할 수 없습니다. 주소와 서버 상태를 확인하세요.", "The GPU server is unreachable. Check the endpoint URL and server status."),
    "err.timeout": ("클라우드 응답 시간이 초과되었습니다.", "The cloud request timed out."),
    "err.invalid_api_key": ("API 키가 올바르지 않습니다. 설정에서 확인하세요.", "The API key is invalid. Check it in Settings."),
    "err.generation_failed": ("생성에 실패했습니다: {detail}", "Generation failed: {detail}"),
    "err.download_interrupted": ("다운로드가 중단되었습니다. 다시 시도하세요.", "The download was interrupted. Please retry."),
    "err.download_too_large": ("다운로드 파일이 너무 큽니다 (제한 {mb} MB).", "The download is too large (limit {mb} MB)."),
    "err.upload_too_large": ("업로드 파일이 너무 큽니다 (제한 {mb} MB).", "The upload is too large (limit {mb} MB)."),
    "err.corrupt_glb": ("GLB 파일이 손상되었거나 올바르지 않습니다.", "The GLB file is corrupt or invalid."),
    "err.corrupt_mesh": ("메시 파일이 올바르지 않습니다.", "The mesh file is invalid."),
    "err.no_mesh": ("파일에서 메시를 찾을 수 없습니다.", "No mesh was found in the file."),
    "err.file_missing": ("파일을 찾을 수 없습니다.", "File not found."),
    "err.file_too_large": ("파일이 너무 큽니다 ({mb} MB).", "The file is too large ({mb} MB)."),
    "err.unsupported_format": ("지원하지 않는 형식입니다: {ext}", "Unsupported format: {ext}"),
    "err.invalid_mesh": ("메시가 출력에 사용할 수 없는 상태입니다.", "The mesh is not usable for printing."),
    "err.export_3mf_failed": ("3MF 변환에 실패했습니다: {detail}", "3MF conversion failed: {detail}"),
    "err.export_failed": ("내보내기에 실패했습니다: {detail}", "Export failed: {detail}"),
    "err.bambu_not_found": ("Bambu Studio를 찾을 수 없습니다. 설정에서 경로를 지정하세요.", "Bambu Studio was not found. Set its path in Settings."),
    "err.bambu_launch_failed": ("Bambu Studio를 실행하지 못했습니다: {detail}", "Could not launch Bambu Studio: {detail}"),
    "err.disk_space": ("디스크 공간이 부족합니다 (필요 {need} MB, 남음 {free} MB).", "Not enough disk space (need {need} MB, {free} MB free)."),
    "err.image_unsupported": ("선택한 공급자는 참조 이미지를 지원하지 않습니다.", "The selected provider does not support reference images."),
    "err.bad_image": ("참조 이미지를 읽을 수 없습니다 (PNG/JPG/WEBP만 가능).", "The reference image cannot be read (PNG/JPG/WEBP only)."),
    "err.bad_endpoint": ("엔드포인트 URL이 올바르지 않습니다.", "The endpoint URL is not valid."),
    "err.no_endpoint": ("엔드포인트 URL이 설정되지 않았습니다. 설정에서 입력하세요.", "No endpoint URL is configured. Enter it in Settings."),
    "err.bad_response": ("서버 응답이 올바르지 않습니다: {detail}", "The server response is invalid: {detail}"),
    "err.no_project": ("열린 프로젝트가 없습니다.", "No project is open."),
    "err.lifecycle_unsupported": ("이 공급자는 GPU 자동 시작/종료를 지원하지 않습니다.", "This provider does not support automatic GPU start/stop."),
    "err.lifecycle_failed": ("GPU 시작/종료에 실패했습니다: {detail}", "GPU start/stop failed: {detail}"),
    "err.demo_only": ("데모 모드에서는 사용할 수 없는 기능입니다.", "This is not available in Demo Mode."),
})

# -------------------------------------------------------------- common UI
_a({
    "ui.error": ("오류", "Error"), "ui.info": ("알림", "Information"), "ui.confirm": ("확인", "Confirm"),
    "ui.retry": ("다시 시도", "Retry"), "ui.close": ("닫기", "Close"), "ui.details": ("자세한 내용", "Details"),
    "ui.save_log": ("로그 저장", "Save log"), "ui.open_settings": ("설정 열기", "Open settings"),
    "ui.browse": ("찾아보기…", "Browse…"), "ui.yes": ("예", "yes"), "ui.no": ("아니오", "no"),
    "ui.pick_color": ("색상 선택", "Pick a color"), "ui.gpu_warning": ("GPU 요금 주의", "GPU billing warning"),
    "nav.generate": ("생성", "Generate"), "nav.library": ("라이브러리", "Library"), "nav.settings": ("설정", "Settings"),
    "nav.new": ("새 프로젝트", "New project"),
    "top.cloud_gpu": ("클라우드 GPU", "Cloud GPU"), "top.stop_gpu": ("GPU 지금 종료", "Stop GPU now"),
    "cloud.disconnected": ("연결 안 됨", "Disconnected"), "cloud.connecting": ("연결 중", "Connecting"),
    "cloud.ready": ("준비됨", "Ready"), "cloud.generating": ("생성 중", "Generating"), "cloud.stopping": ("종료 중", "Stopping"),
    "menu.file": ("파일", "File"), "menu.help": ("도움말", "Help"), "menu.quit": ("종료", "Quit"),
    "menu.open_projects": ("프로젝트 폴더 열기", "Open projects folder"), "menu.open_log": ("로그 폴더 열기", "Open Log Folder"),
    "menu.about": ("FigureCraft 정보", "About FigureCraft"),
    "about.text": ("<b>FigureCraft – AI 3D Figure Maker</b><br>버전 {v}<br><br>텍스트로 3D 프린팅용 피규어를 만드는 데스크톱 앱입니다. "
                   "무거운 AI 생성은 클라우드 GPU에서 실행됩니다.<br>데이터 폴더: {p}",
                   "<b>FigureCraft – AI 3D Figure Maker</b><br>Version {v}<br><br>Desktop app for 3D-printable figures from text. "
                   "Heavy AI generation runs on a cloud GPU.<br>Data folder: {p}"),
    "msg.loading": ("불러오는 중…", "Loading…"),
    "msg.empty_prompt": ("만들고 싶은 피규어를 먼저 설명해 주세요.", "Please describe the figure first."),
    "msg.need_image": ("참조 이미지를 선택하세요.", "Please choose a reference image."),
    "msg.empty_revision": ("수정할 내용을 입력하세요.", "Enter what you want to change."),
    "msg.demo_note": ("데모 모드: AI가 아니라 앱에 포함된 샘플 피규어가 표시됩니다. GPU를 쓰지 않으므로 과금이 없습니다.",
                      "Demo Mode: bundled sample figures are shown - NOT AI output. No GPU is used, so nothing is billed."),
    "msg.demo_badge_tip": ("이 모델은 데모 샘플이며 AI가 생성한 것이 아닙니다.", "This model is a demo sample, not AI generated."),
    "msg.demo_export_note": ("DEMO 샘플입니다 (AI 생성물이 아님). 내보낸 파일에도 DEMO 표시가 들어갑니다.",
                             "DEMO sample (not AI generated). Exported files are marked DEMO too."),
    "msg.demo_revision": ("데모 모드는 모델을 실제로 수정하지 못합니다. 수정 요청은 새 버전에 기록만 됩니다.",
                          "Demo Mode cannot really edit the model. The request is only recorded in a new version."),
    "msg.lifecycle_auto": ("이 공급자는 GPU 자동 시작/종료를 지원합니다.", "This provider supports automatic GPU start/stop."),
    "msg.lifecycle_manual": ("이 공급자는 GPU를 자동으로 끌 수 없습니다. 사용 후 클라우드 콘솔에서 직접 종료하세요.",
                             "This provider cannot stop the GPU automatically. Stop it in your cloud console after use."),
    "msg.gpu_stop_failed": ("GPU를 자동으로 종료하지 못했습니다! 과금이 계속될 수 있습니다.",
                            "The GPU could not be stopped automatically! Billing may continue."),
    "msg.gpu_stopped": ("GPU 종료 요청이 완료되었습니다.", "GPU stop request completed."),
    "msg.quit_generating": ("생성이 진행 중입니다. 취소하고 종료할까요?", "Generation is running. Cancel it and quit?"),
    "msg.quit_gpu_running": ("클라우드 GPU가 아직 켜져 있을 수 있습니다. 종료하지 않으면 계속 과금됩니다.",
                             "The cloud GPU may still be running. It keeps billing until you stop it."),
    "msg.final_check": ("출력 전 Bambu Studio에서 최종 확인하세요. (이 검사는 슬라이서 분석이 아닌 추정입니다)",
                        "Always do the final check in Bambu Studio before printing. (These checks are estimates, not slicer analysis.)"),
    "msg.webgl_failed": ("3D 뷰어를 시작하지 못했습니다 (WebGL 사용 불가). 그래픽 드라이버를 업데이트하세요.",
                         "The 3D viewer could not start (WebGL unavailable). Update your graphics driver."),
    "msg.image_ok_hint": ("PNG / JPG / WEBP 이미지를 선택하세요 (선택 사항).", "Choose a PNG / JPG / WEBP image (optional)."),
    "msg.confirm_revert": ("복구/보정 내용을 모두 버리고 내려받은 원본 상태로 되돌릴까요?",
                           "Discard all repairs/edits and go back to the downloaded original?"),
})

# ----------------------------------------------------------- generate page
_a({
    "gen.prompt_title": ("프롬프트", "Prompt"),
    "gen.mode_text": ("Text to Figure", "Text to Figure"), "gen.mode_image": ("Image + Text to Figure", "Image + Text to Figure"),
    "gen.prompt_placeholder": ("만들고 싶은 피규어를 설명하세요", "Describe the figure you want to make"),
    "gen.insert_example": ("예시 프롬프트 넣기", "Insert example prompt"),
    "gen.pick_image": ("참조 이미지 선택…", "Choose reference image…"),
    "gen.style_size": ("스타일 / 크기", "Style / Size"), "gen.style": ("스타일", "Style"),
    "gen.height": ("높이", "Height"), "gen.custom": ("직접 입력", "Custom"),
    "gen.width_auto": ("너비: 자동", "Width: Auto"), "gen.depth_auto": ("깊이: 자동", "Depth: Auto"),
    "gen.printability": ("3D 프린팅 옵션", "3D printing options"),
    "gen.nozzle": ("노즐 지름", "Nozzle"), "gen.min_feature": ("최소 중요 형상", "Min. important feature"),
    "gen.wall": ("권장 벽/디테일 두께", "Recommended wall/detail"),
    "gen.colors_title": ("프린트 색상 (AMS)", "Print colors (AMS)"), "gen.n_colors": ("{n}색", "{n}"),
    "gen.pal_auto": ("자동 팔레트", "Automatic palette"), "gen.pal_custom": ("사용자 팔레트", "Custom palette"),
    "gen.base_title": ("받침대", "Base"), "gen.base_shape": ("모양", "Shape"),
    "gen.base_thickness": ("받침대 두께", "Base thickness"), "gen.base_margin": ("받침대 여백", "Base margin"),
    "gen.cloud_title": ("클라우드 GPU", "Cloud GPU"),
    "gen.generate": ("피규어 생성", "Generate figure"), "gen.stop": ("중지", "Stop"), "gen.stopping": ("중지하는 중…", "Stopping…"),
    "gen.no_model": ("아직 모델이 없습니다. 프롬프트를 입력하고 생성하세요 (데모 모드에서도 사용 가능).",
                     "No model yet. Enter a prompt and generate (works in Demo Mode too)."),
    "gen.started_at": ("시작: {t}", "Started: {t}"),
    "gen.timing": ("시작 {s} · 완료 {e} · 추정 GPU 사용 시간 {g} {src}", "Started {s} · Completed {e} · Est. GPU active time {g} {src}"),
    "gen.gpu_none": ("(데모: GPU 미사용)", "(demo: no GPU used)"),
    "gen.done_msg": ("완료되었습니다. 출력 전 Bambu Studio에서 최종 확인하세요.", "Done. Always do a final check in Bambu Studio before printing."),
    "opt.flat_bottom": ("바닥 평평하게", "Flat bottom"), "opt.flat_bottom.tip": ("바닥을 평평하게 잘라 베드에 안정적으로 올립니다.", "Cut a flat print plane so the figure sits stably."),
    "opt.add_base": ("받침대 추가", "Add base"), "opt.add_base.tip": ("피규어 아래에 받침대를 붙입니다.", "Attach a base under the figure."),
    "opt.min_thickness_protection": ("최소 두께 보호", "Minimum thickness protection"), "opt.min_thickness_protection.tip": ("얇은 부분을 줄이도록 AI 프롬프트에 요청하고 로컬에서 점검합니다.", "Asks the AI to avoid thin parts and checks locally."),
    "opt.support_friendly": ("서포트 친화적 형상", "Support-friendly geometry"), "opt.support_friendly.tip": ("오버행이 적은 자세를 AI에 요청합니다 (보장 아님).", "Asks the AI for few overhangs (not guaranteed)."),
    "opt.strengthen_thin_parts": ("얇은 부분 보강", "Strengthen thin parts"), "opt.strengthen_thin_parts.tip": ("얇은 영역을 살짝 부풀립니다 (추정 기반, 닫힌 메시에서만).", "Gently thickens thin regions (heuristic, closed meshes only)."),
    "opt.remove_floating": ("떠 있는 조각 제거", "Remove floating geometry"), "opt.remove_floating.tip": ("본체와 떨어진 작은 조각을 지웁니다.", "Removes small pieces detached from the body."),
    "opt.close_holes": ("메시 구멍 메우기", "Close mesh holes"), "opt.close_holes.tip": ("작은 구멍만 안전하게 메웁니다.", "Fills only small holes, safely."),
    "opt.make_watertight": ("가능하면 방수(watertight) 처리", "Make watertight where possible"), "opt.make_watertight.tip": ("복구 후에도 열린 곳이 있으면 경고합니다.", "Warns if openings remain after repair."),
    "opt.simplify_tiny_details": ("작은 디테일 단순화", "Simplify tiny details"), "opt.simplify_tiny_details.tip": ("가볍게 표면을 매끄럽게 합니다.", "Lightly smooths the surface."),
})
for _k, _ko, _en in [("chibi", "치비 / 귀여움", "Chibi / Cute"), ("cartoon_animal", "카툰 동물", "Cartoon Animal"),
                     ("fantasy", "판타지", "Fantasy"), ("anime", "애니풍", "Anime-inspired"), ("mini_figure", "미니 피규어", "Mini Figure"),
                     ("stylized_statue", "스타일라이즈드 조각상", "Stylized Statue"), ("toy", "토이 스타일", "Toy Style"),
                     ("realistic_stylized", "사실적 스타일라이즈드", "Realistic Stylized")]:
    _a({f"style.{_k}": (_ko, _en)})
for _k, _ko, _en in [("none", "없음", "None"), ("round", "원형", "Round"), ("oval", "타원형", "Oval"),
                     ("square", "사각형", "Square"), ("custom", "사용자 지정", "Custom")]:
    _a({f"base.{_k}": (_ko, _en)})
_a({
    "prov.mock": ("데모 (오프라인)", "Demo (offline)"), "prov.generic_http": ("일반 HTTP GPU 서버", "Generic HTTP GPU server"),
    "prov.runpod": ("RunPod", "RunPod"),
    "engine.trellis": ("TRELLIS (MIT 라이선스)", "TRELLIS (MIT license)"),
    "engine.hunyuan3d": ("Hunyuan3D (라이선스 지역 제한 주의)", "Hunyuan3D (check regional license limits)"),
    "engine.mock": ("테스트용 가짜 엔진", "Mock test engine"),
})

# -------------------------------------------------------------- centre/right
_a({
    "view.front": ("앞", "Front"), "view.back": ("뒤", "Back"), "view.left": ("왼쪽", "Left"), "view.right": ("오른쪽", "Right"),
    "view.top": ("위", "Top"), "view.bottom": ("아래", "Bottom"), "view.reset": ("뷰 초기화", "Reset view"),
    "view.original": ("원본 모델", "Original model"), "view.print": ("프린트 색상", "Print colors"),
    "view.parts": ("색상 파트", "Color parts"), "view.wire": ("와이어프레임", "Wireframe"), "view.bbox": ("경계 상자", "Bounding box"),
    "view.mouse_hint": ("회전: 왼쪽 드래그 · 이동: 오른쪽 드래그 · 확대: 휠", "Rotate: left-drag · Pan: right-drag · Zoom: wheel"),
    "info.line": ("크기 {x} × {y} × {z} mm · 꼭짓점 {v} · 삼각형 {t} · {wt} · 구성 요소 {c} · 부피 {vol}",
                  "Size {x} × {y} × {z} mm · Vertices {v} · Triangles {t} · {wt} · Components {c} · Volume {vol}"),
    "info.watertight_yes": ("Watertight 예", "Watertight: yes"), "info.watertight_no": ("Watertight 아니오", "Watertight: no"),
    "right.colors_parts": ("색상 분할 및 파트", "Color split & parts"),
    "right.k_original": ("원본 색", "Original"), "right.k_n": ("{n}색", "{n}-color"),
    "right.add_color": ("+ 색 추가", "+ Add color"), "right.auto_palette": ("자동 팔레트 다시 계산", "Recompute auto palette"),
    "right.rename": ("이름 바꾸기", "Rename"), "right.rename_prompt": ("색상 이름 (3MF 파트 이름에 사용됨):", "Color name (used in 3MF part names):"),
    "right.visible": ("미리보기에서 보이기", "Show in preview"), "right.lock": ("잠금 (자동 팔레트가 바꾸지 않음)", "Lock (auto palette keeps it)"),
    "right.merge": ("다른 색과 병합", "Merge into another color"), "right.delete": ("삭제 (면은 가장 가까운 색으로)", "Delete (faces move to nearest color)"),
    "right.merge_into": ("AMS {n} {name}(으)로 병합", "Merge into AMS {n} {name}"),
    "right.parts_hint": ("파트 = 같은 색으로 이어진 영역. 표에서 고르거나 3D 화면을 클릭한 뒤 AMS 색을 바꿀 수 있습니다.",
                         "A part is a connected region of one color. Pick it in the table or click it in 3D, then change its AMS color."),
    "right.part": ("파트", "Part"), "right.area": ("면적", "Area"), "right.ams": ("AMS 색", "AMS color"),
    "right.validation": ("메시 검사", "Mesh validation"), "right.no_report": ("모델 없음", "No model"),
    "status.GOOD": ("GOOD 양호", "GOOD"), "status.CHECK": ("CHECK 확인 필요", "CHECK"), "status.FAILED": ("FAILED 실패", "FAILED"),
    "right.tools": ("복구 / 출력 보정", "Repair / print tools"),
    "right.repair": ("안전 복구 실행", "Run safe repair"), "right.revert": ("원본으로 되돌리기", "Revert to original"),
    "right.flat_preview": ("바닥 평평하게 (미리보기)", "Flat bottom (preview)"), "right.flat_apply": ("적용", "Apply"),
    "right.add_base": ("받침대 붙이기", "Attach base"), "right.strengthen": ("얇은 부분 보강", "Strengthen thin parts"),
    "right.repair_done": ("복구 완료:", "Repair finished:"), "right.reverted": ("원본 상태로 되돌렸습니다.", "Reverted to the original."),
    "right.base_added": ("받침대를 붙였습니다 ({how}).", "Base attached ({how})."),
    "right.strengthened": ("{n}개 꼭짓점 영역을 보강했습니다.", "Strengthened around {n} vertices."),
    "right.strengthen_none": ("보강이 필요한 얇은 부분을 찾지 못했습니다 (또는 닫힌 메시가 아님).", "No thin parts needing reinforcement were found (or the mesh is not closed)."),
    "flat.already": ("바닥이 이미 평평합니다 (접촉 면적 {a} mm²).", "The bottom is already flat (contact area {a} mm²)."),
    "flat.plan": ("제안: 바닥에서 {z} mm 위에서 자름 → 접촉 면적 약 {a} mm², 부피 약 {v}% 제거. 빨간 면이 자르는 위치입니다.",
                  "Proposal: cut {z} mm above the lowest point → contact area ≈ {a} mm², ≈ {v}% volume removed. The red plane shows the cut."),
    "flat.none": ("안정적인 평면을 만들 만한 얕은 절단 위치가 없습니다. 받침대를 추가해 보세요.", "No shallow cut gives a stable plane. Try adding a base."),
    "flat.applied": ("바닥을 평평하게 잘랐습니다.", "Flat bottom applied."), "flat.failed": ("절단에 실패해 변경하지 않았습니다.", "The cut failed; nothing was changed."),
    "right.revision": ("모델 수정 요청", "Model revision request"),
    "right.revision_ph": ("예: 귀를 더 크게 만들어줘", "e.g. make the ears bigger"),
    "right.revision_examples": ("예시 선택…", "Pick an example…"),
    "right.send_revision": ("수정 요청 보내기 (새 버전으로 저장)", "Send revision (saved as a new version)"),
    "right.open_version": ("이 버전 열기", "Open this version"),
    "right.export": ("내보내기", "Export"),
    "right.mode_multipart": ("멀티파트 3MF (권장)", "Multipart 3MF (recommended)"), "right.mode_color": ("색상 3MF", "Color 3MF"),
    "right.mode_multipart.tip": ("색마다 닫힌 파트로 나눈 3MF. Bambu Studio에서 파트별로 AMS 필라멘트를 지정합니다.", "3MF split into closed parts per color; assign an AMS filament to each part in Bambu Studio."),
    "right.mode_color.tip": ("삼각형마다 색 정보가 있는 3MF 1개 객체. Bambu Studio가 색을 못 읽으면 멀티파트를 쓰세요.", "A single 3MF object with per-triangle colors. If Bambu Studio ignores them, use Multipart."),
    "right.save_3mf": ("3MF 저장", "Save 3MF"), "right.stl_by_color": ("색상별 STL", "STL per color"),
    "right.open_bambu": ("Bambu Studio에서 열기", "Open in Bambu Studio"),
    "export.saved": ("저장됨: {f}", "Saved: {f}"), "export.saved_n": ("{n}개 파일 저장됨: {d}", "{n} files saved: {d}"),
    "export.bambu_opened": ("Bambu Studio를 실행했습니다.", "Launched Bambu Studio."),
    "export.report": ("3MF 검증 통과 ({method}) · 객체 {objs}개 · 삼각형 {tris} · 작성기: {backend}",
                      "3MF validated ({method}) · {objs} objects · {tris} triangles · writer: {backend}"),
    "export.method.solid": ("닫힌 색상별 솔리드 파트", "closed solid color parts"),
    "export.method.shell": ("표면 조각 파트", "surface-shell parts"),
    "export.method.per-triangle": ("삼각형별 색상", "per-triangle colors"),
    "export.shell_note": ("이 모델은 닫힌 솔리드가 아니어서 표면 조각 파트로 저장했습니다. 슬라이서에서 '모델 수리'가 필요할 수 있으니 색상 3MF도 시도해 보세요.",
                          "This model is not a closed solid, so the parts are surface shells. The slicer may need to repair them - also try the Color 3MF."),
})

# --------------------------------------------------- issues / repair texts
_a({
    "issue.none": ("발견된 문제가 없습니다.", "No problems found."),
    "issue.empty": ("메시가 비어 있습니다.", "The mesh is empty."),
    "issue.degenerate_model": ("모델이 너무 작거나 납작합니다.", "The model is too small or flat."),
    "issue.degenerate_faces": ("퇴화 삼각형 {n}개", "{n} degenerate triangles"),
    "issue.duplicate_faces": ("중복 면 {n}개", "{n} duplicate faces"),
    "issue.non_manifold": ("비다양체(non-manifold) 모서리 {n}개", "{n} non-manifold edges"),
    "issue.open_edges": ("열린 모서리 {n}개 (구멍)", "{n} open edges (holes)"),
    "issue.not_watertight": ("Watertight가 아닙니다.", "Not watertight."),
    "issue.tiny_components": ("아주 작은 떠다니는 조각 {n}개", "{n} microscopic floating fragments"),
    "issue.floating": ("본체와 떨어진 조각 {n}개 (공중에 뜬 부분 가능)", "{n} pieces detached from the body (may float in mid-air)"),
    "issue.multi_component": ("서로 닿아 있는 구성 요소 {n}개", "{n} touching components"),
    "issue.flat_bottom_missing": ("평평한 바닥이 부족합니다 (접촉 면적 {area} mm²).", "Not enough flat bottom (contact {area} mm²)."),
    "issue.overhangs": ("45° 초과 오버행 면적 약 {pct}% → 서포트가 생길 수 있음", "About {pct}% of the area overhangs > 45° → supports likely"),
    "issue.thin_features": ("{mm} mm보다 얇은 부분이 {n}곳 (부피의 {pct}%) – 추정", "{n} spots thinner than {mm} mm ({pct}% of volume) – estimate"),
    "issue.thin_skipped": ("열린 메시라 얇은 부분 검사를 건너뛰었습니다.", "Thin-feature check skipped (mesh is not closed)."),
    "issue.thin_info": ("얇은 부분 추정 비율: {pct}%", "Estimated thin-region share: {pct}%"),
    "repair.nothing": ("고칠 것이 없었습니다.", "Nothing needed fixing."),
    "repair.nonfinite": ("잘못된 좌표 면 {n}개 제거", "removed {n} faces with invalid coordinates"),
    "repair.degenerate": ("퇴화 면 {n}개 제거", "removed {n} degenerate faces"),
    "repair.duplicates": ("중복 면 {n}개 제거", "removed {n} duplicate faces"),
    "repair.weld": ("가까운 꼭짓점 {n}개 병합", "merged {n} coincident vertices"),
    "repair.winding": ("면 방향 정리", "fixed face winding"), "repair.inversion": ("뒤집힌 법선 수정", "fixed inverted normals"),
    "repair.fragments": ("작은 조각 {n}개 제거", "removed {n} small fragments"),
    "repair.holes_filled": ("작은 구멍 {n}개 메움", "filled {n} small holes"),
    "repair.holes_left": ("큰 구멍 {n}개는 그대로 둠", "left {n} large openings untouched"),
    "repair.smoothed": ("표면 살짝 다듬음", "lightly smoothed the surface"),
})

# ----------------------------------------------------------- library / settings
_a({
    "lib.title": ("프로젝트 라이브러리", "Project library"), "lib.empty": ("프로젝트가 없습니다. 생성 탭에서 데모 피규어를 만들어 보세요.", "No projects yet. Try a demo figure on the Generate tab."),
    "lib.count": ("프로젝트 {n}개", "{n} projects"), "lib.colors": ("{n}색", "{n} colors"),
    "lib.open": ("열기", "Open"), "lib.rename": ("이름 변경", "Rename"), "lib.duplicate": ("복제", "Duplicate"),
    "lib.delete": ("삭제", "Delete"), "lib.export": ("내보내기 (ZIP)", "Export (ZIP)"), "lib.open_folder": ("폴더 열기", "Open folder"),
    "lib.rename_prompt": ("새 이름:", "New name:"), "lib.confirm_delete": ("이 프로젝트를 영구 삭제할까요?", "Delete this project permanently?"),
    "lib.status.ready": ("완료", "Ready"), "lib.status.failed": ("실패", "Failed"), "lib.status.running": ("진행 중", "Running"), "lib.status.empty": ("비어 있음", "Empty"),
    "set.title": ("설정", "Settings"), "set.general": ("일반", "General"), "set.language": ("언어", "Language"),
    "set.theme": ("테마", "Theme"), "set.theme_dark": ("어두운 테마", "Dark"), "set.theme_light": ("밝은 테마", "Light"),
    "set.project_dir": ("프로젝트 폴더", "Project folder"),
    "set.cloud": ("클라우드 GPU", "Cloud GPU"), "set.provider": ("공급자", "Provider"), "set.endpoint": ("엔드포인트 URL", "Endpoint URL"),
    "set.api_key": ("API 키", "API key"), "set.key_ph": ("API 키 입력 (암호화 저장)", "Enter API key (stored encrypted)"),
    "set.key_saved": ("저장됨 (바꾸려면 새 키 입력)", "Saved (enter a new key to replace)"),
    "set.key_env": ("환경변수 FIGURECRAFT_API_KEY 사용 중", "Using environment variable FIGURECRAFT_API_KEY"),
    "set.rp_key": ("RunPod 계정 API 키 (Pod 시작/종료용)", "RunPod account API key (Pod start/stop)"),
    "set.rp_key_ph": ("Pod 모드에서만 필요 (암호화 저장)", "Only for Pod mode (stored encrypted)"),
    "set.key_delete": ("키 삭제", "Delete key"), "set.engine": ("모델 엔진", "Model engine"), "set.timeout": ("제한 시간", "Timeout"),
    "set.pod": ("RunPod Pod ID (선택)", "RunPod Pod ID (optional)"), "set.pod_ph": ("Pod 모드일 때만 입력", "Only for Pod mode"),
    "set.auto_stop": ("생성 완료 후 GPU 자동 종료", "Auto-stop GPU after generation"),
    "set.test": ("연결 테스트", "Test connection"), "set.testing": ("연결 중…", "Connecting…"),
    "set.test_ok": ("연결됨 ({ms} ms) · 엔진 {engine} · 참조 이미지 {img} · 원격 종료 {life}", "Connected ({ms} ms) · engine {engine} · reference image {img} · remote stop {life}"),
    "set.cloud_hint": ("API 키는 이 PC에서 암호화되어 저장되며 로그에 남지 않습니다. 환경변수 FIGURECRAFT_API_KEY가 있으면 그것을 우선 사용합니다.",
                       "The API key is stored encrypted on this PC and never logged. The FIGURECRAFT_API_KEY environment variable takes priority."),
    "set.printing": ("3D 프린팅 기본값", "3D printing defaults"), "set.default_height": ("기본 모델 높이", "Default model height"),
    "set.default_colors": ("기본 색상 수", "Default number of colors"),
    "set.bambu": ("Bambu Studio", "Bambu Studio"), "set.bambu_path": ("실행 파일 경로", "Executable path"),
    "set.bambu_ph": ("자동 감지 실패 – 직접 선택하세요", "Not detected – choose it manually"), "set.bambu_detect": ("자동 감지", "Auto-detect"),
    "set.default_3mf": ("기본 3MF 방식", "Default 3MF mode"), "set.ams_presets": ("AMS 색상 프리셋 (사용자 팔레트 기본값)", "AMS color preset (default custom palette)"),
    "set.save": ("설정 저장", "Save settings"), "set.saved": ("설정을 저장했습니다.", "Settings saved."),
})
