// =====================================================================
//  Stump Planter  -  self-watering planter with a bark outer pot
//  Autumn Nest contest, entry #8 (A Forest Corner: planters)
//
//  Two pots, one inside the other (a "double pot" / sub-irrigation planter):
//    - the OUTER pot is a watertight reservoir with a bark-textured outside. It is generated by
//      tools/bark_shell.py (stl/shell.stl), because the bark relief is a 170 000 triangle surface.
//    - the INNER pot (this file, part = "pot") holds the soil and hangs from the rim of the outer pot
//      on three tabs. Its floor stays 8 mm above the highest possible water level.
//    - three cotton wicks run from the soil, through the floor of the inner pot, down into the water.
//      The soil drinks as it needs it; the water cannot rot the roots because the pot never sits in it.
//    - the three gaps between the tabs are the filling slots; the dipstick (part = "dipstick") stands in one
//      of them and shows the water level. An overflow hole in the outer pot, 30 mm above the floor,
//      sets the highest water level: pour until it drips and the reservoir is exactly full.
//
//  DRAINAGE: six 3 mm holes in the floor of the inner pot let excess water run out of the soil into the
//  reservoir (the pot is never watertight), and the overflow hole lets the reservoir drain
//  before it can reach the inner pot. Use a free-draining potting mix.
//
//  The numbers marked [shell] must match tools/bark_shell.py.
//  Tested with OpenSCAD 2021.01.
// =====================================================================

/* [Part to render] */
// pot = inner pot, dipstick = water level stick (flat, ready to print), dipstick_asm = same stick standing in the planter (for renders and checks)
part = "pot"; // [pot, dipstick, dipstick_asm]

/* [Outer pot (shell) - fixed by bark_shell.py] */
// inner radius of the reservoir [shell]
shell_ri = 47;
// smooth wall thickness [shell]
shell_wall = 3.2;
// height of the outer pot [shell]
shell_h = 100;
// floor thickness [shell]
shell_floor = 3;
// height of the middle of the overflow hole [shell]
overflow_z = 32.5;
overflow_d = 5;

/* [Inner pot] */
// outside radius of the inner pot body
pot_ro = 42;
// wall thickness (6 perimeters of 0.4 mm)
pot_wall = 2.4;
// floor thickness
pot_floor = 3;
// total height of the inner pot
pot_h = 66;
// height of the pot's underside above the outer pot's floor: the cone seat touches the rim at shell_h
pot_z = 38;
// the three tabs: arc length of each (degrees); the rest are the filling slots
tab_arc = 70;
tab_angles = [90, 210, 330];
// wicks: number, hole diameter, circle radius (cotton rope 4 to 6 mm, knot the end that stays in the soil)
wick_n = 3;
wick_d = 6.5;
wick_r = 15;
// drain holes
drain_n = 6;
drain_d = 3;
drain_r = 26;

/* [Dipstick] */
stick_t = 3;            // radial thickness (the slot between the pots is 5 mm)
stick_w = 5;            // width
stick_r = 43;           // inner face of the stick in the planter
stick_angle = 150;      // in the middle of the slot between two tabs
stick_tip_z = shell_floor + 0.4;
stick_head_z = 110;     // where the leaf head starts, above the rim of the inner pot (104)
leaf_l = 24;
leaf_w = 20;
mark_w = 0.9;           // groove width
mark_d = 0.7;           // groove depth

/* [Quality] */
$fn = 120;

pot_ri = pot_ro - pot_wall;
seat_z = shell_h - pot_z;                 // height in the pot's frame where the cone passes the rim edge (62)
assert(pot_ro + 4 <= shell_ri, "less than 4 mm slot between the pots");
assert(pot_h >= seat_z + 2, "pot too short for the tabs");
assert(drain_r + drain_d / 2 < pot_ri - 2 && wick_r + wick_d / 2 < drain_r - 2);

// ---- inner pot ------------------------------------------------------
// a tab is a segment of a 45 degree cone: its underside touches the inner top edge of the outer pot,
// so the pot centres itself and no overhang is steeper than 45 degrees. (r - z) is constant on the cone.
module tab() {
    k = shell_ri - seat_z;                              // r = z + k
    z0 = pot_ro - 1 - k;                                // cone height at r = pot_ro - 1 (inside the pot wall)
    z1 = pot_h;
    rotate_extrude(angle = tab_arc, $fn = 180)
        polygon([[pot_ro - 1, z0], [z1 + k, z1], [pot_ro - 1, z1]]);
}

module pot() {
    difference() {
        union() {
            cylinder(r = pot_ro, h = pot_h);
            for (a = tab_angles) rotate(a - tab_arc / 2) tab();
        }
        translate([0, 0, pot_floor]) cylinder(r = pot_ri, h = pot_h);
        for (i = [0 : wick_n - 1])
            rotate(i * 360 / wick_n + 30) translate([wick_r, 0, -1]) cylinder(d = wick_d, h = pot_floor + 2, $fn = 48);
        for (i = [0 : drain_n - 1])
            rotate(i * 360 / drain_n) translate([drain_r, 0, -1]) cylinder(d = drain_d, h = pot_floor + 2, $fn = 32);
    }
}

// ---- dipstick -------------------------------------------------------
// printed flat: x = length (the tip at x = 0), y = width (centred), z = thickness
stick_len = stick_head_z - stick_tip_z;

function leaf_profile(n = 40) = let(
    right = [for (i = [0 : n]) let(t = i / n)
        [leaf_l * t, leaf_w / 2 * pow(sin(180 * pow(t, 0.8)), 0.8) * (1 + 0.16 * cos(360 * 2.5 * t) * sin(180 * t))]],
    left = [for (i = [n - 1 : -1 : 1]) [right[i][0], -right[i][1]]]
) concat(right, left);

module marks() {
    // MAX: the bottom of the overflow hole; LOW: top up before it falls below this line
    max_x = (overflow_z - overflow_d / 2) - stick_tip_z;
    low_x = 10 - stick_tip_z;
    translate([max_x - mark_w / 2, -stick_w, stick_t - mark_d]) cube([mark_w, 2 * stick_w, 1]);
    translate([low_x - mark_w / 2, -stick_w, stick_t - mark_d]) cube([mark_w, stick_w * 1.0, 1]);
    // pitch every 5 mm below the MAX line as a ruler: short ticks
    for (x = [max_x - 5 : -5 : 5])
        if (abs(x - low_x) > 2) translate([x - mark_w / 2, -stick_w / 2 - 0.01, stick_t - 0.45]) cube([mark_w, stick_w / 2 + 0.01, 1]);
}

module dipstick() {
    difference() {
        union() {
            translate([0, -stick_w / 2, 0]) cube([stick_len + 1, stick_w, stick_t]);
            translate([stick_len, 0, 0]) linear_extrude(stick_t) polygon(leaf_profile());
        }
        marks();
        // midrib of the leaf head, engraved
        translate([stick_len + 3, -0.4, stick_t - 0.6]) cube([leaf_l - 7, 0.8, 1]);
    }
}

module dipstick_asm() {
    // print frame -> planter frame: x -> up, z -> radial, y -> -tangential
    rotate(stick_angle)
        multmatrix([[0, 0, 1, stick_r], [0, -1, 0, 0], [1, 0, 0, stick_tip_z], [0, 0, 0, 1]]) dipstick();
}

if (part == "dipstick") dipstick();
else if (part == "dipstick_asm") dipstick_asm();
else pot();

echo(str("inner pot: radius ", pot_ro, ", height ", pot_h, "; its underside sits ", pot_z, " mm above the outer pot floor"));
echo(str("slot between the pots ", shell_ri - pot_ro, " mm; dipstick length ", stick_len + leaf_l, " mm"));
